### ISSUE TITLE
update needed for 2019 unity version

### ISSUE THREAD

**Issue by SilencedSoppu** [HookedBehemoth/WorldCleanup#2]
world cleanup loads up with melon loader but does not add the ability to play with a players toggles/parameters, the menu is just empty, unless something was changed the code needs to be rechecked/updated for the new version of Unity that VRChat is using now.
also many newer versions of melonloader are now being used.
Much appreciated if you get this done, the wait will be worth it.

**Comment by HookedBehemoth** [comment]
Thanks! New release published.
See https://github.com/HookedBehemoth/ubiquitous-guide/releases/latest
