### ISSUE TITLE
Failed to load parameter config

### ISSUE THREAD

**Issue by Weeeeeee-e** [HookedBehemoth/WorldCleanup#3]
![image](https://user-images.githubusercontent.com/89716486/131236605-469bf22b-1c31-4ee5-b2fe-00895b6ad8b9.png)
Im getting this error despite having the most recent updates for UI Expansion Kit and Action Menu API.

**Comment by HookedBehemoth** [comment]
This should only appear the first time when the config file doesn't exist yet. Does this persist?
